# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux
  - osx
warnings_are_errors: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgsl0-dev; fi
language: R
r_github_packages:
  kforner/rcpp_progress
cache: packages
