// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppGSL)]]
#include <RcppGSL.h>
// [[Rcpp::depends(RcppProgress)]]
#include <progress.hpp>
#ifdef _OPENMP
#include <omp.h>
#endif
// [[Rcpp::plugins(openmp)]]
#include "class_mixed_shape_curve.h"
#include "class_mixed_shape_model.h"

//' Internal function for fitting the model by SAEM
//'
//' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
//'        for the time and value of the functional data
//' @param pars_list List with components: mu, kappa, tau and sigma2
//' @param control_list List generated by control_saem()
//' @param y_scl_r Numeric value for scaling back the estimates and predictions to the original scale of y
//' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
// [[Rcpp::export]]
Rcpp::List saem_fit_mixed_shape(Rcpp::List curve_list,
                                Rcpp::List pars_list,
                                Rcpp::List control_list,
                                double y_scl_r,
                                bool trace) {

  // Create counters
  int saem_idx = 0;
  int curve_idx = 0;

  int seed = Rcpp::as<int>(control_list["seed"]);

  // Special handling of f_break_points as an RcppGSL::Vector object to be propergated to the classes
  RcppGSL::Vector f_break_points = Rcpp::as< RcppGSL::vector<double> >(control_list["f_knots"]);

  Rcpp::Rcout << "Import parameters" << std::endl;
  // Import parameters
  Mixed_Shape_Model* pars = new Mixed_Shape_Model(pars_list, control_list, y_scl_r, f_break_points);

  Rcpp::Rcout << "Import data" << std::endl;
  // Import data
  std::vector<Mixed_Shape_Curve*>* data = new std::vector<Mixed_Shape_Curve*>;
  data->reserve(pars->n_curve);
  for(Rcpp::List::iterator it = curve_list.begin(); it != curve_list.end(); ++it) {
    data->push_back(new Mixed_Shape_Curve(*it, pars, curve_idx, y_scl_r, seed));
    ++curve_idx;
  }

  Rcpp::Rcout << "Initialize basis evaluation matrices" << std::endl;
  // Initialize basis evaluation matrices
  for(std::vector<Mixed_Shape_Curve*>::iterator it = data->begin(); it != data->end(); ++it){
    (*it)->initialize_f_basis_mat();
  }


  // Setup multi-threading
#ifdef _OPENMP
  omp_set_num_threads(pars->n_core);
  REprintf("Number of threads=%i\n", omp_get_max_threads());
#endif


  // Setup progress tracking
  int tick = std::max(1, (int) pars->n_iterations / 20);
  Progress p(0, false);
  double progress;


  if(trace){
    pars->print_estimates(1);
  }

  Rcpp::Rcout << "Entering SAEM loop..." << std::endl;
  // SAEM loop
  for(saem_idx = 0; saem_idx < pars->n_iterations; ++saem_idx){
    // Simulation step
//#pragma omp parallel for
    for(std::vector<Mixed_Shape_Curve*>::iterator it = data->begin(); it != data->end(); ++it){
      (*it)->do_MH_simulation_step();
    }
    // Maximization step
    pars->update_parameter_estimates(data);
    pars->track_estimates();
    // Progress report
    if (pars->saem_counter % tick == 0) {
      progress = (double) pars->saem_counter / pars->n_iterations * 100;
      Rprintf("%3.1f%%...", progress);
      if(trace){
        pars->print_estimates(1);
      }
    }
    pars->advance_iteration_counter();
    if (Progress::check_abort())
      saem_idx = pars->n_iterations; // Bump index to exit the loop
  }
  Rcpp::Rcout << "(Done)" << std::endl;


  // Wrap up as R objects
  Rcpp::List curves(pars->n_curve);
  Rcpp::List est_pars;
  Rcpp::List aux;
  Rcpp::List pars_track;
  for(curve_idx = 0; curve_idx < pars->n_curve; ++curve_idx){
    curves[curve_idx] = data->at(curve_idx)->return_list();
  }
  est_pars = pars->return_pars();
  aux = pars->return_aux();
  pars_track = pars->return_pars_tracker();

  // Free memory
  for(std::vector<Mixed_Shape_Curve*>::iterator it = data->begin(); it != data->end(); ++it){
    delete *it;
  }
  free(data);
  free(pars);

  // Return to R
  return(Rcpp::List::create(
      Rcpp::Named("pars", est_pars),
      Rcpp::Named("curves", curves),
      Rcpp::Named("aux", aux),
      Rcpp::Named("pars_track", pars_track)));

}




