# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for fitting the model by SAEM
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa, tau and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
saem_fit <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('mixedWarpedCurves2_saem_fit', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

#' Internal function for fitting the model by SAEM
#'
#' @export
test_gsl_rng_multithread <- function(curve_list, pars_list, control_list, y_scaling_factor) {
    invisible(.Call('mixedWarpedCurves2_test_gsl_rng_multithread', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor))
}

