# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for MLE of dirichlet distribution by newton-raphson
#'
#' @param w_list R List - list of compositional data points
#' @export
dirichlet_mle <- function(w_list) {
    .Call('_mixedWarpedCurves2_dirichlet_mle', PACKAGE = 'mixedWarpedCurves2', w_list)
}

#' Internal function for fitting mixture of Dirichlet by EM
#'
#' @param data matrix of data point on simplex
#' @param init_clust initial cluster label
#' @param dim_m number of mixture components
#' @param maxit number of EM iterations
#' @export
em_mixture_of_dirichlet <- function(data, init_clust, dim_m, maxit) {
    .Call('_mixedWarpedCurves2_em_mixture_of_dirichlet', PACKAGE = 'mixedWarpedCurves2', data, init_clust, dim_m, maxit)
}

logLik_unimodal <- function(pars_list, curve_list, aux_list, mc_mode, n_mc, seed) {
    .Call('_mixedWarpedCurves2_logLik_unimodal', PACKAGE = 'mixedWarpedCurves2', pars_list, curve_list, aux_list, mc_mode, n_mc, seed)
}

#' Internal function for fitting the model by SAEM
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa, tau and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('_mixedWarpedCurves2_saem_fit', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

#' Internal function for fitting the model by SAEM
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa, tau and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scl_r Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit_mixed_shape <- function(curve_list, pars_list, control_list, y_scl_r, trace) {
    .Call('_mixedWarpedCurves2_saem_fit_mixed_shape', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scl_r, trace)
}

#' Internal function for fitting the model by SAEM
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit_mixed_warped_curves <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('_mixedWarpedCurves2_saem_fit_mixed_warped_curves', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

#' Internal function for fitting the model by SAEM
#' (obsolete/incorrect implementation)
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit_mixed_warping <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('_mixedWarpedCurves2_saem_fit_mixed_warping', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

#' Internal function for fitting the model by SAEM
#' (obsolete and experimental, probably an incorrect implementation)
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa, tau and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit_mixture_a_model <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('_mixedWarpedCurves2_saem_fit_mixture_a_model', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

#' Internal function for fitting the model by SAEM
#'
#' @param curve_list List of curve objects, each should have a component called data, with subcomponents, x and y,
#'        for the time and value of the functional data
#' @param pars_list List with components: mu, kappa and sigma2
#' @param control_list List generated by control_saem()
#' @param y_scaling_factor Numeric value for scaling back the estimates and predictions to the original scale of y
#' @param trace Logical value, if TRUE tracing information of the estimated parameters are printed
saem_fit_unimodal <- function(curve_list, pars_list, control_list, y_scaling_factor, trace) {
    .Call('_mixedWarpedCurves2_saem_fit_unimodal', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list, y_scaling_factor, trace)
}

