# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

saem_fit <- function(curve_list, pars_list, control_list) {
    .Call('mixedWarpedCurves2_saem_fit', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list)
}

test_oopc1 <- function(curve_list, pars_list, control_list) {
    invisible(.Call('mixedWarpedCurves2_test_oopc1', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list))
}

test_oopc <- function(curve_list, pars_list, control_list) {
    .Call('mixedWarpedCurves2_test_oopc', PACKAGE = 'mixedWarpedCurves2', curve_list, pars_list, control_list)
}

